[package]
name = "rust-rasterizer"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.30.0"
# glam = { version = "0.30", default-features = false, features = ["scalar-math", "std"] }
minifb = "0.28.0"
minifb_fonts = "0.1"
rand = "0.9.0"
byteorder = "1.5.0"

[profile.release]
debug = true